Dispatch cmmn engine events when task is assigned #2744
flowable/flowable-engine pull request #2794
Opened 2021-02-05 18:56 UTC by DavidPLamas

#### Check List:
* Unit tests: YES
* Documentation: NO

2021-02-05 19:00 UTC, dbmalkovsky commented on modules/flowable-cmmn-api/src/main/java/org/flowable/cmmn/api/event/FlowableTaskAssignedEvent.java
> +package org.flowable.cmmn.api.event;
Please add the standard license header to all new files; thanks.

2021-02-06 16:11 UTC, filiphr requested changes
Thanks for the PR @DavidPLamas. 

It looks great, I have only one small remark. I don't think that we need a new `FlowableTaskAssignedEvent` class since there are a lot of other places where we throw the task assigned event with a `FlowableEngineEntityEvent` instead. 

Can you please adapt your changes to match the way it is done currently?

2021-02-08 13:15 UTC, DavidPLamas commented
Hi @filiphr,

I've removed the FlowableTaskAssignedEvent and started using FlowableEntityEvent instead. I was gonna copy the code from ```org.flowable.engine.delegate.event.impl.FlowableEventBuilder#createEntityEvent``` but I thought it was too much.
Let me know if there is anything else that needs changing.

2021-02-19 09:54 UTC, DavidPLamas commented
Hi,
It's been a while, I just noticed the build has failed. From looking at the error log, it doesn't seem to be because of my changes.
Is there any way to retrigger the build to check if it was just a temporary problem?

2021-02-19 09:58 UTC, filiphr commented
Thanks for the ping @DavidPLamas. No need to retrigger. The Windows build is a bit unstable. The other builds look good

2021-02-19 10:25 UTC, filiphr commented
I manually merged this in https://github.com/flowable/flowable-engine/commit/86f818f37eca2f2c06ea2e66f1340ba51e0308db

2021-02-19 10:25 UTC, closed without merging