WIP: #2937 mailbehaviour charset
flowable/flowable-engine pull request #2979
Opened 2021-07-11 09:37 UTC by ddpardo

Implementation to support default charset from configuration.

#### Check List:
* Unit tests: YES (partial)
* Documentation: YES (javadoc)

2021-07-11 10:19 UTC, dbmalkovsky commented on modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/behavior/impl/MailActivityBehavior.java
> +        }else{
This is a nitpick but please follow project standards for formatting.  For example spaces before and after braces and parentheses.  Thanks.  

There are formatting files for IntelliJ and Eclipse in https://github.com/flowable/flowable-engine/tree/master/ide-settings

2021-07-12 07:14 UTC, filiphr requested changes
This looks as expected @ddpardo. I've left a comment in one place about a typo.

Please finish the tests for CMMN and the comment given by @dbmalkovsky and we'll merge this.

btw, I see that there is some conflict in the MailActivityBehavior as well, can you please resolve that as well?

2021-07-12 07:14 UTC, filiphr commented on modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/behavior/impl/MailActivityBehavior.java
> +    protected void setCharset(Email email, String charSetStr, String tentantId) {
Typo in the parameter name. It should be `tenantId`

2021-08-17 12:31 UTC, closed without merging

2021-08-17 12:32 UTC, filiphr commented
Thanks for the PR @ddpardo. Since we are closing to our release, I took this and finished it