盘古BPM 批量查询支持
flowable/flowable-engine pull request #3057
Opened 2021-09-25 03:32 UTC by qiudaoke

#### Check List:
* Unit tests: YES / NO / NA
* Documentation: YES / NO / NA

2021-09-25 08:12 UTC, dbmalkovsky commented on modules/flowable-engine/src/test/java/org/flowable/standalone/testing/FlowableTestTaskInQueryTest.java
> +import static org.assertj.core.api.Assertions.assertThat;
Thanks for the PR.

Please follow project coding standards for imports; see https://github.com/flowable/flowable-engine/tree/main/ide-settings.  

The standard order is:

- static imports
- java
- javax
- org
- com
- everything else

2022-01-20 07:28 UTC, filiphr requested changes
Thanks a lot for the PR @qiudaoke. For some reason I missed it, sorry for the late review.

I've left some comments that would be good to be addressed before merging this.

In addition to that will you have time to expose this to the REST API as well? In the:

* `org.flowable.cmmn.rest.service.api.runtime.task.TaskCollectionResource`
* `org.flowable.cmmn.rest.service.api.history.task.HistoricTaskInstanceCollectionResource`
* `org.flowable.cmmn.rest.service.api.runtime.task.TaskQueryResource`
* `org.flowable.rest.service.api.runtime.task.TaskCollectionResource`
* `org.flowable.rest.service.api.history.HistoricTaskInstanceCollectionResource`
* `org.flowable.rest.service.api.runtime.task.TaskQueryResource`

If not we can add it separately later

2022-01-20 07:28 UTC, filiphr commented on modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/HistoricTaskInstanceQueryImpl.java
> +        }
I don't think that we need to do this, we are not doing it for any other collection

2022-01-20 07:28 UTC, filiphr commented on modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/HistoricTaskInstanceQueryImpl.java
> +     */
please move the javadoc to the interface only

2022-01-20 07:28 UTC, filiphr commented on modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/TaskQueryImpl.java
> +     */
Please move the javadoc to the interface only

2022-01-20 07:28 UTC, filiphr commented on modules/flowable-task-service/src/main/java/org/flowable/task/service/impl/TaskQueryImpl.java
> +        }
Same comment as in the history query. We don't do this for any other collection, so we can remove it

2022-01-20 07:28 UTC, filiphr commented on modules/flowable-task-service-api/src/main/java/org/flowable/task/api/TaskInfoQuery.java
> +
This is obsolete

2022-01-20 07:28 UTC, filiphr commented on modules/flowable-task-service/src/main/resources/org/flowable/task/service/db/mapping/entity/HistoricTaskInstance.xml
> +    <if test="taskIdList != null &amp;&amp; taskIdList.size() &gt; 0">
We recently did a change when checking for a size of a list. please use `!taskIdList.empty` instead.

2022-01-20 07:28 UTC, filiphr commented on modules/flowable-task-service/src/main/resources/org/flowable/task/service/db/mapping/entity/Task.xml
> +        <foreach item="taskId" index="index" collection="taskIdList"
We recently did a change when checking for a size of a list. please use `!taskIdList.empty` instead.

2022-01-20 07:28 UTC, filiphr commented on modules/flowable-engine/src/test/resources/org/flowable/standalone/testing/FlowableTestTaskInQueryTest.testSimpleProcess.bpmn20.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This is not needed, you can reuse one of the current one task processes.

2022-01-20 07:28 UTC, filiphr commented on modules/flowable-engine/src/test/java/org/flowable/standalone/testing/FlowableTestTaskInQueryTest.java
> +    public void testSimpleProcess() {
Can you please move this test ot the `TaskQueryTest` we don't need another test class for this

2022-01-20 07:30 UTC, filiphr commented
@qiudaoke can you please rebase the PR on top of main as well, we did some changes in the XML files and there are some conflicts now

2022-02-23 05:15 UTC, qiudaoke commented
> @qiudaoke can you please rebase the PR on top of main as well, we did some changes in the XML files and there are some conflicts now
see this pr
https://github.com/flowable/flowable-engine/pull/3224

2022-12-20 18:15 UTC, filiphr commented
Closing this since PR #3224

2022-12-20 18:15 UTC, closed without merging