UI Modeler cannot import reactivate event listener
flowable/flowable-engine pull request #3191
Opened 2022-01-27 09:37 UTC by aplatakis

Issue:
It is not possible to import reactivate event listener in modeler UI. If cmmn diagram contains such element, then after import it is dropped and is not present in UI
Modeler UI not allows to add reactivate event listener using UI

Cause:
Reactivate event listener do not have json converter implemented.

Details:
Reactivate event listener is using the same tag "EventListener" as generic event listener. EventType="reactivate" is used to configure it as reactivate event listener

Solution:
* To distinguish between generic and reactivate listeners UI checkbox introduced. Now it is possible to add in that way reactivate event listener using UI
* For reactivate event listener to import registered new json converter which maps listener to "EventListener" stencilId.
* For export it is complexity as two json converters try to handle "EventListener" stencilId. So generic event listener json converter unregistered for export handling and logic now is handled by reactivate event listener json converter
* For event registry support reactivation event listener can accept eventType

#### Check List:
* Unit tests: NA
* Documentation: NA

2022-02-09 12:35 UTC, tijsrademakers commented
Thanks for the PR, but for the reactivate event listener a dedicated element type would be needed, so not sharing it with a generic event listener. Would that be something you would be willing to work on?

2022-02-09 12:59 UTC, aplatakis commented
@tijsrademakers thanks for review. First idea was to use new element type, but when I realized that I would need to introduce new icon for that, I dropped the idea. But I do agree that new element type would be better as this would drop not needed configuration options in UI, bring more clarity in UI and code and so on. I will change my code to use new element type
I have question regarding languages support. Is it enough to add localized values only for en? Will this not cause issues for other existing languages? As I'm not sure that google translate is the best option here.. For some languages I see that not all UI elements are translated

2022-03-07 13:22 UTC, aplatakis commented on modules/flowable-cmmn-engine/src/main/java/org/flowable/cmmn/engine/impl/behavior/impl/ReactivateEventListenerActivityBehaviour.java
> +import org.flowable.cmmn.engine.impl.util.PlanItemInstanceUtil;
Good catch. Thank you. Fixed

2022-12-20 11:08 UTC, filiphr requested changes
thanks @aplatakis.

I see that the `ReactivateEventListener` is still extending from the `GenericEventListener`. That doesn't make sense. Can you please remove all the changes from the XML converter and CMMN engine and only have changes in the UI Modeler code. There, should be no need to change anything in the XML conversion and CMMN Engine for this functionality to work.

2022-12-20 11:08 UTC, filiphr commented on modules/flowable-cmmn-converter/src/main/java/org/flowable/cmmn/converter/export/ReactivationEventListenerExport.java
> +        if (StringUtils.isNotEmpty(reactivationEventListener.getEventType()) && reactivationEventListener.getExtensionElements().get("eventType") == null) {
Why do we need this change? there is already an exported flowable attribute with listener type `reactivate` on line 45. Perhaps the JSON conversion should use that instead.

2023-10-09 06:22 UTC, tijsrademakers commented
Closing because Modeler is not part of Flowable 7 codebase.

2023-10-09 06:22 UTC, closed without merging