ProcessInstanceCollectionResource  and CaseInstanceCollectionResource…
flowable/flowable-engine pull request #3956
Opened 2024-09-06 14:09 UTC by WelschChristopher

… now support sending transientVariables,variables and startFormVariables in one request.

#### Check List:
* Unit tests: YES / NO / NA
* Documentation: YES / NO / NA

2024-09-06 16:30 UTC, dbmalkovsky commented on modules/flowable-cmmn-rest/src/test/java/org/flowable/cmmn/rest/service/api/runtime/TransientVariableServiceTask.java
> +package org.flowable.cmmn.rest.service.api.runtime;
Missing the license header block.

2024-09-06 16:31 UTC, dbmalkovsky commented on modules/flowable-rest/src/test/java/org/flowable/rest/service/api/runtime/TransientVariableServiceTask.java
> +package org.flowable.rest.service.api.runtime;
Missing the license header block.

2024-10-02 14:14 UTC, filiphr requested changes

2024-10-02 14:14 UTC, filiphr commented on modules/flowable-engine/src/test/java/org/flowable/engine/test/api/variables/TransientVariablesTest.java
> +        }
This is not needed, please remove it

2024-10-03 11:15 UTC, filiphr approved these changes

2024-10-03 11:21 UTC, merged